name: GitHub actions demo
run-name: Testing our Github actions

on: [push]
env:
  owner_name: Ratan
  ratan_repo_value: ${{vars.owner_name}}

jobs:
  basic_workflow:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job basic_workflow is executing as part of new workflow from $owner_name"
